---
- name: Install Nginx
  hosts: nginx_servers
  become: yes
  debugger: on_failed
  tasks:

  - name: Install Nginx on CentOS
    yum:
      name=nginx
      state=latest
    when:
      ansible_os_family == "RedHat"

  - name: Install Nginx on Ubuntu
    apt:
      name=nginx
      state=latest
    when:
      ansible_os_family == "Debian"

  - name: Stop Nginx
    service:
      name: nginx
      state: stopped
      enabled: no
    ignore_errors: yes


  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes
