---
- name: Install Apache
  hosts: apache_servers
  become: yes
  debugger: on_failed
  tasks:

  - name: Include vars for os family
    include_vars:
      file: "../vars/{{ ansible_os_family }}.yml"

  - name: Install Apache on CentOS 8
    yum:
      name: "{{ service_name }}"
      state: present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install Apache on Ubuntu
    apt:
      name: "{{ service_name }}"
      state: present
    when: ansible_os_family == 'Debian'

  - name: Stop Apache
    service:
      name: "{{ service_name }}"
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: Start Apache
    service:
      name: "{{ service_name }}"
      state: started
      enabled: yes
    ignore_errors: yes
