---
- name: Install Zabbix agent
  hosts: zabbix_agents
  become: yes
  debugger: on_failed
  tasks:

    - name: Install Zabbix agent on CentOS 8
      yum:
        name: https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-3.el8.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: Install Zabbix agent on Ubuntu
      apt:
        deb: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4+ubuntu20.04_all.deb
      when: ansible_distribution == 'Ubuntu'

    - name: Install Zabbix agent package
      package:
        name: zabbix-agent
        state: present

    - name: Change Server IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        line: "Server=zabbix.sf-admin-gusevnv.local"

        #    - name: Change Active Server IP
        #      lineinfile:
        #        path: /etc/zabbix/zabbix_agentd.conf
        #        regexp: 'ServerActive=127.0.0.1'
        #        line: "ServerActive=zabbix.sf-admin-gusevnv.local"

    - name: Change hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Hostname=Zabbix server'
        line: Hostname={{ ansible_hostname }}

    - name: Stop zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
        enabled: no
      ignore_errors: yes


    - name: Start zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
